name: Hello World Workflow

on:
  issue_comment:
    types: [created]

jobs:
  reply-to-comment:
    if: contains(github.event.comment.body, '/hello')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Reply with message
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.issue.number }}
          body: '👋 Hello! I am a bot powered by GitHub Actions!'
